### ISSUE TITLE
Support puppet-server

### ISSUE THREAD

**Issue by stephenrjohnson** [stephenrjohnson/puppetmodule#62]
Just wondering if anyone is using this in production yet? https://github.com/puppetlabs/puppet-server

**Comment by stefanandres** [comment]
bump :)

**Comment by rauchrob** [comment]
Since the Rack-Based Puppetmaster-Stack is deprecated in favour of puppet-server, we should definitely implement support for puppetserver. Maybe we could integrate the functionality of [camptocamp/puppetserver](https://github.com/camptocamp/puppet-puppetserver) or make this module at least compatible with it.

Personally, I stopped using stephenrjohnson/puppet::master yesterday because I migrated to puppetserver.
